"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-09-24 21:35:12.689694
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "card_batches",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("chip_type", sa.String(length=16), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_card_batches")),
    )
    op.create_table(
        "spaces",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("type", sa.String(length=16), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("currency_name", sa.String(length=32), nullable=False),
        sa.Column("currency_icon", sa.String(length=8), nullable=False),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column("allow_negative", sa.Boolean(), nullable=False),
        sa.Column("daily_transfer_limit", sa.Integer(), nullable=True),
        sa.Column("transfer_approval_threshold", sa.Integer(), nullable=True),
        sa.Column("offline_spend_limit", sa.Integer(), nullable=True),
        sa.Column("seq", sa.BigInteger(), nullable=False),
        sa.Column("updated_seq", sa.BigInteger(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("type IN ('family', 'organization')", name=op.f("ck_spaces_type")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_spaces")),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(length=254), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("locale", sa.String(length=8), nullable=False),
        sa.Column("pin_salt", sa.String(length=64), nullable=True),
        sa.Column("pin_hash", sa.String(length=128), nullable=True),
        sa.Column("pin_iterations", sa.Integer(), nullable=True),
        sa.Column("email_verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("email", name=op.f("uq_users_email")),
    )
    op.create_table(
        "devices",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("space_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("last_sync_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("pending_ops", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["space_id"], ["spaces.id"], name=op.f("fk_devices_space_id_spaces"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_devices_user_id_users")),
        sa.PrimaryKeyConstraint("id", "space_id", name=op.f("pk_devices")),
    )
    op.create_table(
        "email_tokens",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("purpose", sa.String(length=16), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("purpose IN ('verify', 'reset')", name=op.f("ck_email_tokens_purpose")),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_email_tokens_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_email_tokens")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_email_tokens_token_hash")),
    )
    op.create_index(op.f("ix_email_tokens_user_id"), "email_tokens", ["user_id"], unique=False)
    op.create_table(
        "game_templates",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("space_id", sa.UUID(), nullable=True),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("starting_capital", sa.Integer(), nullable=False),
        sa.Column("quick_buttons", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["space_id"],
            ["spaces.id"],
            name=op.f("fk_game_templates_space_id_spaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_game_templates")),
    )
    op.create_index(
        op.f("ix_game_templates_space_id"), "game_templates", ["space_id"], unique=False
    )
    op.create_table(
        "players",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("space_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=40), nullable=False),
        sa.Column("avatar", sa.String(length=32), nullable=False),
        sa.Column("birth_year", sa.SmallInteger(), nullable=True),
        sa.Column("group_name", sa.String(length=40), nullable=True),
        sa.Column("consent_user_id", sa.UUID(), nullable=False),
        sa.Column("consent_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("seq", sa.BigInteger(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["consent_user_id"], ["users.id"], name=op.f("fk_players_consent_user_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["space_id"], ["spaces.id"], name=op.f("fk_players_space_id_spaces"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_players")),
    )
    op.create_index(op.f("ix_players_space_id"), "players", ["space_id"], unique=False)
    op.create_table(
        "products",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("space_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("emoji", sa.String(length=8), nullable=True),
        sa.Column("price", sa.Integer(), nullable=False),
        sa.Column("stock", sa.Integer(), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("seq", sa.BigInteger(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("price > 0", name=op.f("ck_products_price_positive")),
        sa.ForeignKeyConstraint(
            ["space_id"],
            ["spaces.id"],
            name=op.f("fk_products_space_id_spaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_products")),
    )
    op.create_index(op.f("ix_products_space_id"), "products", ["space_id"], unique=False)
    op.create_table(
        "refresh_tokens",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_refresh_tokens_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_refresh_tokens")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_refresh_tokens_token_hash")),
    )
    op.create_index(op.f("ix_refresh_tokens_user_id"), "refresh_tokens", ["user_id"], unique=False)
    op.create_table(
        "space_members",
        sa.Column("space_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "role IN ('owner', 'admin', 'operator')", name=op.f("ck_space_members_role")
        ),
        sa.ForeignKeyConstraint(
            ["space_id"],
            ["spaces.id"],
            name=op.f("fk_space_members_space_id_spaces"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_space_members_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("space_id", "user_id", name=op.f("pk_space_members")),
    )
    op.create_index(op.f("ix_space_members_user_id"), "space_members", ["user_id"], unique=False)
    op.create_table(
        "allowances",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("space_id", sa.UUID(), nullable=False),
        sa.Column("player_id", sa.UUID(), nullable=True),
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.Column("comment", sa.String(length=80), nullable=False),
        sa.Column("weekday", sa.SmallInteger(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("last_run_on", sa.Date(), nullable=True),
        sa.Column("created_by", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("amount > 0", name=op.f("ck_allowances_amount_positive")),
        sa.CheckConstraint("weekday BETWEEN 0 AND 6", name=op.f("ck_allowances_weekday")),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_allowances_created_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["player_id"],
            ["players.id"],
            name=op.f("fk_allowances_player_id_players"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["space_id"],
            ["spaces.id"],
            name=op.f("fk_allowances_space_id_spaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_allowances")),
    )
    op.create_index(op.f("ix_allowances_space_id"), "allowances", ["space_id"], unique=False)
    op.create_table(
        "cards",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("token", sa.String(length=32), nullable=False),
        sa.Column("uid", sa.String(length=32), nullable=True),
        sa.Column("chip_type", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("batch_id", sa.UUID(), nullable=True),
        sa.Column("activation_code_hash", sa.String(length=64), nullable=True),
        sa.Column("space_id", sa.UUID(), nullable=True),
        sa.Column("player_id", sa.UUID(), nullable=True),
        sa.Column("label", sa.String(length=40), nullable=True),
        sa.Column("activated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("blocked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("seq", sa.BigInteger(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(status IN ('active', 'blocked')) = (player_id IS NOT NULL)",
            name=op.f("ck_cards_active_has_player"),
        ),
        sa.CheckConstraint(
            "chip_type IN ('ntag213', 'ntag215', 'ntag216', 'ntag424')", name=op.f("ck_cards_chip")
        ),
        sa.CheckConstraint(
            "status IN ('in_stock', 'active', 'blocked', 'unlinked')", name=op.f("ck_cards_status")
        ),
        sa.ForeignKeyConstraint(
            ["batch_id"], ["card_batches.id"], name=op.f("fk_cards_batch_id_card_batches")
        ),
        sa.ForeignKeyConstraint(
            ["player_id"],
            ["players.id"],
            name=op.f("fk_cards_player_id_players"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["space_id"], ["spaces.id"], name=op.f("fk_cards_space_id_spaces"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cards")),
        sa.UniqueConstraint("token", name=op.f("uq_cards_token")),
    )
    op.create_index(op.f("ix_cards_player_id"), "cards", ["player_id"], unique=False)
    op.create_index(op.f("ix_cards_space_id"), "cards", ["space_id"], unique=False)
    op.create_index(
        "ix_cards_uid", "cards", ["uid"], unique=True, postgresql_where=sa.text("uid IS NOT NULL")
    )
    op.create_table(
        "device_links",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("player_id", sa.UUID(), nullable=False),
        sa.Column("code_hash", sa.String(length=64), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_device_links_created_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["player_id"],
            ["players.id"],
            name=op.f("fk_device_links_player_id_players"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_device_links")),
        sa.UniqueConstraint("code_hash", name=op.f("uq_device_links_code_hash")),
    )
    op.create_table(
        "game_sessions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("space_id", sa.UUID(), nullable=False),
        sa.Column("template_id", sa.UUID(), nullable=True),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("money_mode", sa.String(length=16), nullable=False),
        sa.Column("starting_capital", sa.Integer(), nullable=False),
        sa.Column("quick_buttons", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=False),
        sa.Column("device_id", sa.UUID(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("seq", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "money_mode IN ('reset', 'persistent')", name=op.f("ck_game_sessions_money_mode")
        ),
        sa.CheckConstraint(
            "status IN ('lobby', 'active', 'paused', 'finished')",
            name=op.f("ck_game_sessions_status"),
        ),
        sa.CheckConstraint("starting_capital >= 0", name=op.f("ck_game_sessions_capital")),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_game_sessions_created_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["space_id"],
            ["spaces.id"],
            name=op.f("fk_game_sessions_space_id_spaces"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["template_id"],
            ["game_templates.id"],
            name=op.f("fk_game_sessions_template_id_game_templates"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_game_sessions")),
    )
    op.create_index(op.f("ix_game_sessions_space_id"), "game_sessions", ["space_id"], unique=False)
    op.create_table(
        "player_devices",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("player_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["player_id"],
            ["players.id"],
            name=op.f("fk_player_devices_player_id_players"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_player_devices")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_player_devices_token_hash")),
    )
    op.create_index(
        op.f("ix_player_devices_player_id"), "player_devices", ["player_id"], unique=False
    )
    op.create_table(
        "savings_goals",
        sa.Column("player_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=60), nullable=False),
        sa.Column("target_amount", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["player_id"],
            ["players.id"],
            name=op.f("fk_savings_goals_player_id_players"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("player_id", name=op.f("pk_savings_goals")),
    )
    op.create_table(
        "wallets",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("space_id", sa.UUID(), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("player_id", sa.UUID(), nullable=True),
        sa.Column("session_id", sa.UUID(), nullable=True),
        sa.Column("balance", sa.BigInteger(), nullable=False),
        sa.Column("flagged", sa.Boolean(), nullable=False),
        sa.Column("flag_reason", sa.String(length=64), nullable=True),
        sa.Column("seq", sa.BigInteger(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(kind = 'session') = (session_id IS NOT NULL)", name=op.f("ck_wallets_session")
        ),
        sa.CheckConstraint(
            "(kind IN ('persistent', 'session')) = (player_id IS NOT NULL)",
            name=op.f("ck_wallets_owner"),
        ),
        sa.CheckConstraint(
            "kind IN ('persistent', 'session', 'bank', 'shop')", name=op.f("ck_wallets_kind")
        ),
        sa.ForeignKeyConstraint(
            ["player_id"], ["players.id"], name=op.f("fk_wallets_player_id_players")
        ),
        sa.ForeignKeyConstraint(
            ["session_id"], ["game_sessions.id"], name=op.f("fk_wallets_session_id_game_sessions")
        ),
        sa.ForeignKeyConstraint(
            ["space_id"], ["spaces.id"], name=op.f("fk_wallets_space_id_spaces"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_wallets")),
    )
    op.create_index(op.f("ix_wallets_space_id"), "wallets", ["space_id"], unique=False)
    op.create_index(
        "uq_wallet_persistent",
        "wallets",
        ["player_id"],
        unique=True,
        postgresql_where=sa.text("kind = 'persistent'"),
    )
    op.create_index(
        "uq_wallet_session",
        "wallets",
        ["player_id", "session_id"],
        unique=True,
        postgresql_where=sa.text("kind = 'session'"),
    )
    op.create_index(
        "uq_wallet_system",
        "wallets",
        ["space_id", "kind"],
        unique=True,
        postgresql_where=sa.text("kind IN ('bank', 'shop')"),
    )
    op.create_table(
        "session_participants",
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column("player_id", sa.UUID(), nullable=False),
        sa.Column("wallet_id", sa.UUID(), nullable=False),
        sa.Column("space_id", sa.UUID(), nullable=False),
        sa.Column("joined_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("seq", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["player_id"], ["players.id"], name=op.f("fk_session_participants_player_id_players")
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["game_sessions.id"],
            name=op.f("fk_session_participants_session_id_game_sessions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["space_id"], ["spaces.id"], name=op.f("fk_session_participants_space_id_spaces")
        ),
        sa.ForeignKeyConstraint(
            ["wallet_id"], ["wallets.id"], name=op.f("fk_session_participants_wallet_id_wallets")
        ),
        sa.PrimaryKeyConstraint("session_id", "player_id", name=op.f("pk_session_participants")),
    )
    op.create_table(
        "transactions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("space_id", sa.UUID(), nullable=False),
        sa.Column("type", sa.String(length=16), nullable=False),
        sa.Column("from_wallet_id", sa.UUID(), nullable=False),
        sa.Column("to_wallet_id", sa.UUID(), nullable=False),
        sa.Column("amount", sa.BigInteger(), nullable=False),
        sa.Column("session_id", sa.UUID(), nullable=True),
        sa.Column("card_id", sa.UUID(), nullable=True),
        sa.Column("reverses_id", sa.UUID(), nullable=True),
        sa.Column("operator_id", sa.UUID(), nullable=True),
        sa.Column("player_device_id", sa.UUID(), nullable=True),
        sa.Column("device_id", sa.UUID(), nullable=True),
        sa.Column("comment", sa.String(length=140), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "received_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("offline", sa.Boolean(), nullable=False),
        sa.Column("seq", sa.BigInteger(), nullable=False),
        sa.CheckConstraint(
            "(type = 'reversal') = (reverses_id IS NOT NULL)", name=op.f("ck_transactions_reversal")
        ),
        sa.CheckConstraint(
            "type IN ('credit', 'debit', 'transfer', 'purchase', 'reversal', 'session_start', 'prize', 'allowance')",
            name=op.f("ck_transactions_type"),
        ),
        sa.CheckConstraint("amount > 0", name=op.f("ck_transactions_amount_positive")),
        sa.CheckConstraint(
            "from_wallet_id <> to_wallet_id", name=op.f("ck_transactions_distinct_wallets")
        ),
        sa.ForeignKeyConstraint(
            ["card_id"], ["cards.id"], name=op.f("fk_transactions_card_id_cards")
        ),
        sa.ForeignKeyConstraint(
            ["from_wallet_id"], ["wallets.id"], name=op.f("fk_transactions_from_wallet_id_wallets")
        ),
        sa.ForeignKeyConstraint(
            ["operator_id"], ["users.id"], name=op.f("fk_transactions_operator_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["player_device_id"],
            ["player_devices.id"],
            name=op.f("fk_transactions_player_device_id_player_devices"),
        ),
        sa.ForeignKeyConstraint(
            ["reverses_id"],
            ["transactions.id"],
            name=op.f("fk_transactions_reverses_id_transactions"),
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["game_sessions.id"],
            name=op.f("fk_transactions_session_id_game_sessions"),
        ),
        sa.ForeignKeyConstraint(
            ["space_id"],
            ["spaces.id"],
            name=op.f("fk_transactions_space_id_spaces"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["to_wallet_id"], ["wallets.id"], name=op.f("fk_transactions_to_wallet_id_wallets")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_transactions")),
        sa.UniqueConstraint("reverses_id", name=op.f("uq_transactions_reverses_id")),
    )
    op.create_index(
        op.f("ix_transactions_session_id"), "transactions", ["session_id"], unique=False
    )
    op.create_index("ix_tx_from", "transactions", ["from_wallet_id", "created_at"], unique=False)
    op.create_index("ix_tx_space_seq", "transactions", ["space_id", "seq"], unique=False)
    op.create_index("ix_tx_to", "transactions", ["to_wallet_id", "created_at"], unique=False)
    op.create_table(
        "transfer_requests",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("space_id", sa.UUID(), nullable=False),
        sa.Column("from_player_id", sa.UUID(), nullable=False),
        sa.Column("to_player_id", sa.UUID(), nullable=False),
        sa.Column("amount", sa.BigInteger(), nullable=False),
        sa.Column("comment", sa.String(length=140), nullable=True),
        sa.Column("player_device_id", sa.UUID(), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("decided_by", sa.UUID(), nullable=True),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("transaction_id", sa.UUID(), nullable=True),
        sa.Column("seq", sa.BigInteger(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'approved', 'rejected')",
            name=op.f("ck_transfer_requests_status"),
        ),
        sa.CheckConstraint("amount > 0", name=op.f("ck_transfer_requests_amount_positive")),
        sa.ForeignKeyConstraint(
            ["decided_by"], ["users.id"], name=op.f("fk_transfer_requests_decided_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["from_player_id"],
            ["players.id"],
            name=op.f("fk_transfer_requests_from_player_id_players"),
        ),
        sa.ForeignKeyConstraint(
            ["player_device_id"],
            ["player_devices.id"],
            name=op.f("fk_transfer_requests_player_device_id_player_devices"),
        ),
        sa.ForeignKeyConstraint(
            ["space_id"],
            ["spaces.id"],
            name=op.f("fk_transfer_requests_space_id_spaces"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["to_player_id"], ["players.id"], name=op.f("fk_transfer_requests_to_player_id_players")
        ),
        sa.ForeignKeyConstraint(
            ["transaction_id"],
            ["transactions.id"],
            name=op.f("fk_transfer_requests_transaction_id_transactions"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_transfer_requests")),
    )
    op.create_index(
        op.f("ix_transfer_requests_space_id"), "transfer_requests", ["space_id"], unique=False
    )
    # ### end Alembic commands ###

    templates = sa.table(
        "game_templates",
        sa.column("id", sa.UUID()),
        sa.column("name", sa.String()),
        sa.column("starting_capital", sa.Integer()),
        sa.column("quick_buttons", postgresql.JSONB()),
        sa.column("sort_order", sa.Integer()),
    )
    op.bulk_insert(
        templates,
        [
            {
                "id": "3f0b6f38-1d2a-4a53-9a51-0e7d4b1c0001",
                "name": "Настольная экономическая игра",
                "starting_capital": 1500,
                "quick_buttons": [
                    {"label": "50", "amount": 50, "type": "debit"},
                    {"label": "100", "amount": 100, "type": "debit"},
                    {"label": "За круг 200", "amount": 200, "type": "credit"},
                ],
                "sort_order": 1,
            },
            {
                "id": "3f0b6f38-1d2a-4a53-9a51-0e7d4b1c0002",
                "name": "Магазин и рынок",
                "starting_capital": 500,
                "quick_buttons": [
                    {"label": "10", "amount": 10, "type": "debit"},
                    {"label": "50", "amount": 50, "type": "debit"},
                ],
                "sort_order": 2,
            },
            {
                "id": "3f0b6f38-1d2a-4a53-9a51-0e7d4b1c0003",
                "name": "Своя игра",
                "starting_capital": 1000,
                "quick_buttons": [],
                "sort_order": 3,
            },
        ],
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_transfer_requests_space_id"), table_name="transfer_requests")
    op.drop_table("transfer_requests")
    op.drop_index("ix_tx_to", table_name="transactions")
    op.drop_index("ix_tx_space_seq", table_name="transactions")
    op.drop_index("ix_tx_from", table_name="transactions")
    op.drop_index(op.f("ix_transactions_session_id"), table_name="transactions")
    op.drop_table("transactions")
    op.drop_table("session_participants")
    op.drop_index(
        "uq_wallet_system",
        table_name="wallets",
        postgresql_where=sa.text("kind IN ('bank', 'shop')"),
    )
    op.drop_index(
        "uq_wallet_session", table_name="wallets", postgresql_where=sa.text("kind = 'session'")
    )
    op.drop_index(
        "uq_wallet_persistent",
        table_name="wallets",
        postgresql_where=sa.text("kind = 'persistent'"),
    )
    op.drop_index(op.f("ix_wallets_space_id"), table_name="wallets")
    op.drop_table("wallets")
    op.drop_table("savings_goals")
    op.drop_index(op.f("ix_player_devices_player_id"), table_name="player_devices")
    op.drop_table("player_devices")
    op.drop_index(op.f("ix_game_sessions_space_id"), table_name="game_sessions")
    op.drop_table("game_sessions")
    op.drop_table("device_links")
    op.drop_index("ix_cards_uid", table_name="cards", postgresql_where=sa.text("uid IS NOT NULL"))
    op.drop_index(op.f("ix_cards_space_id"), table_name="cards")
    op.drop_index(op.f("ix_cards_player_id"), table_name="cards")
    op.drop_table("cards")
    op.drop_index(op.f("ix_allowances_space_id"), table_name="allowances")
    op.drop_table("allowances")
    op.drop_index(op.f("ix_space_members_user_id"), table_name="space_members")
    op.drop_table("space_members")
    op.drop_index(op.f("ix_refresh_tokens_user_id"), table_name="refresh_tokens")
    op.drop_table("refresh_tokens")
    op.drop_index(op.f("ix_products_space_id"), table_name="products")
    op.drop_table("products")
    op.drop_index(op.f("ix_players_space_id"), table_name="players")
    op.drop_table("players")
    op.drop_index(op.f("ix_game_templates_space_id"), table_name="game_templates")
    op.drop_table("game_templates")
    op.drop_index(op.f("ix_email_tokens_user_id"), table_name="email_tokens")
    op.drop_table("email_tokens")
    op.drop_table("devices")
    op.drop_table("users")
    op.drop_table("spaces")
    op.drop_table("card_batches")
    # ### end Alembic commands ###
